-- Existing grants were created from non-reconstructable random values. Revoke
-- them instead of risking replay of a stale credential after this migration.
UPDATE "session_upload_grants"
SET "status" = 'REVOKED', "revoked_at" = COALESCE("revoked_at", CURRENT_TIMESTAMP)
WHERE "status" = 'ACTIVE';

UPDATE "print_sessions"
SET
  "state" = 'CANCELED',
  "state_version" = "state_version" + 1,
  "terminal_reason" = 'SECURITY_MIGRATION',
  "canceled_at" = COALESCE("canceled_at", CURRENT_TIMESTAMP),
  "updated_at" = CURRENT_TIMESTAMP
WHERE "state" NOT IN ('COMPLETED', 'CANCELED', 'EXPIRED');

-- Purge legacy replay rows because create responses contained raw QR values and
-- their keys cannot be converted to the new context-bound HMAC without the
-- application pepper. This is an intentional one-time idempotency reset.
DELETE FROM "idempotency_records";

-- New rows contain a context-bound HMAC generated by the API, never the raw
-- idempotency key.
DROP INDEX "idempotency_records_actor_id_action_key_key";
ALTER TABLE "idempotency_records" RENAME COLUMN "key" TO "key_digest";
ALTER TABLE "idempotency_records"
  ALTER COLUMN "key_digest" TYPE VARCHAR(64);
ALTER TABLE "idempotency_records"
  ADD CONSTRAINT "idempotency_records_key_digest_check"
  CHECK ("key_digest" ~ '^[0-9a-f]{64}$');
CREATE UNIQUE INDEX "idempotency_records_actor_id_action_key_digest_key"
  ON "idempotency_records"("actor_id", "action", "key_digest");

ALTER TABLE "idempotency_records"
  ADD CONSTRAINT "idempotency_records_create_response_sanitized_check"
  CHECK (
    "action" <> 'sessions.create'
    OR (
      "response_body" ? 'session'
      AND ("response_body" - 'session') = '{}'::jsonb
    )
  );
